const AfricaPL = {
    "AO": "Angola",
    "BI": "Burundi",
    "BJ": "Benin",
    "BF": "Burkina Faso",
    "BW": "Botswana",
    "CF": "Republika Środkowoafrykańska",
    "CI": "Wybrzeże Kości Słoniowej",
    "CM": "Kamerun",
    "CD": "Demokratyczna Republika Konga",
    "CG": "Republika Konga",
    "DJ": "Dzibuti",
    "DZ": "Algieria",
    "EG": "Egipt",
    "ER": "Erytrea",
    "ET": "Etiopia",
    "GA": "Gabon",
    "GH": "Ghana",
    "GN": "Gwinea",
    "GM": "Gambia",
    "GW": "Gwinea Bissau",
    "GQ": "Gwinea Równikowa",
    "KE": "Kenia",
    "LR": "Liberia",
    "LY": "Libia",
    "LS": "Lesotho",
    "MA": "Moroko",
    "MG": "Madagaskar",
    "ML": "Mali",
    "MZ": "Mozambik",
    "MR": "Mauretania",
    "MW": "Malawi",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "RW": "Rwanda",
    "EH": "Sahara Zachodnia",
    "SD": "Sudan",
    "SS": "Sudan Południowy",
    "SN": "Senegal",
    "SL": "Sierra Leone",
    "SZ": "Suazi",
    "TD": "Czad",
    "TG": "Togo",
    "TN": "Tunezja",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "ZA": "Republika Południowej Afryki",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    "SO": "Somalia"
  }

export { AfricaPL };
