const Europe = {
	"AL": "Albania",
	"AD": "Andorra",
	"AT": "Austria",
	"BE": "Belgium",
	"BG": "Bulgaria",
	"BA": "Bosnia and Herz.",
	"BY": "Belarus",
	"CH": "Switzerland",
	"CZ": "Czech Rep.",
	"CY": "Cyprus",
	"DE": "Germany",
	"DK": "Denmark",
	"EE": "Estonia",
	"FI": "Finland",
	"GB": "United Kingdom",
	"GR": "Greece",
	"HR": "Croatia",
	"HU": "Hungary",
	"IE": "Ireland",
	"IS": "Iceland",
	"IT": "Italy",
	"LI": "Liechtenstein",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"LV": "Latvia",
	"MD": "Moldova",
	"MK": "Macedonia",
	"ME": "Montenegro",
	"NL": "Netherlands",
	"NO": "Norway",
	"PL": "Poland",
	"PT": "Portugal",
	"RO": "Romania",
	"RS": "Serbia",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"SE": "Sweden",
	"TR": "Turkey",
	"UA": "Ukraine",
	"FR": "France",
	"ES": "Spain",
	"XK": "Kosovo"
};
export {Europe};
