const EuropePL = {
	"AL": "Albania",
	"AD": "Andora",
	"AT": "Austria",
	"BE": "Belgia",
	"BG": "Bułgaria",
	"BA": "Bośnia i Hercegowina",
	"BY": "Białoruś",
	"CH": "Szwajcaria",
	"CZ": "Czechy",
	"CY": "Cypr",
	"DE": "Niemcy",
	"DK": "Dania",
	"EE": "Estonia",
	"FI": "Finlandia",
	"GB": "Wielka Brytania",
	"GR": "Grecja",
	"HR": "Chorwacja",
	"HU": "Węgry",
	"IE": "Irlandia",
	"IS": "Islandia",
	"IT": "Włochy",
	"LI": "Liechtenstein",
	"LT": "Litwa",
	"LU": "Luksemburg",
	"LV": "Łotwa",
	"MD": "Mołdawia",
	"MK": "Macedonia",
	"ME": "Czarnogóra",
	"NL": "Holandia",
	"NO": "Norwegia",
	"PL": "Polska",
	"PT": "Portugalia",
	"RO": "Rumunia",
	"RS": "Serbia",
	"SK": "Słowacja",
	"SI": "Słowenia",
	"SE": "Szwecja",
	"TR": "Turcja",
	"UA": "Ukraina",
	"FR": "Francja",
	"ES": "Hiszpania",
	"XK": "Kosowo"
}
export {EuropePL};
